# Generated by Django 4.2.9 on 2024-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ChainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
